[build]
  command = "npm install && npm run build:ssr"
  publish = "dist/circuit-on/browser"
  port = 4000


[[redirects]]
  from = "/*"
  to = "/index.html"
  force = true
  status = 200

[dev]
  command = "npm run serve:ssr"
  port = 4000
  publish = "dist/circuit-on/browser"