name: Deploy to Netlify Hosting on merge
"on":
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build:ssr
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./dist/propaganda-scheduler/browser"
          production-branch: dev
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          netlify-config-path: "./netlify.toml"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
